name: Bug report
description: Report a reproducible defect in Recurgent
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please provide a minimal reproducible case.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What happened?
      placeholder: Describe the observed behavior.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction
      description: Minimal steps/code to reproduce.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: input
    id: runtime
    attributes:
      label: Runtime
      description: Runtime and version (for example, ruby 3.4.7)
    validations:
      required: true
  - type: textarea
    id: diagnostics
    attributes:
      label: Diagnostics
      description: Test/lint output or error traces.
    validations:
      required: true
