AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 160
  Exclude:
    - "lib/recurgent/artifact_store.rb"
    - "lib/recurgent/pattern_memory.rb"
    - "lib/recurgent/guardrail_policy.rb"
    - "lib/recurgent/outcome_contract.rb"
    - "lib/recurgent/tool_store.rb"
    - "lib/recurgent/observability.rb"
    - "lib/recurgent/conversation_history.rb"
    - "lib/recurgent/fresh_generation.rb"
    - "lib/recurgent/prompting.rb"

Metrics/AbcSize:
  Max: 25

Metrics/ParameterLists:
  Max: 8

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 150

Security/Eval:
  Exclude:
    - "lib/recurgent/worker_entrypoint.rb"
