AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 45

Metrics/ClassLength:
  Max: 300

Metrics/AbcSize:
  Max: 25

Metrics/ParameterLists:
  Max: 8

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 150

Security/Eval:
  Exclude:
    - "lib/recurgent.rb"
